variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-GCC
  - build-Clang
  - quality
  - deploy

include:
  - "/.gitlab/ci/build.yml"
  - "/.gitlab/ci/deploy.yml"
  - "/.gitlab/ci/quality.yml"
