variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_IMAGE_GCC: embeddedlinux/gcc:11
  DOCKER_IMAGE_CLANG: embeddedlinux/clang:13
  DOCKER_IMAGE_ARM_LINUX_GCC: embeddedlinux/arm-linux-gnueabihf-gcc:10
  DOCKER_IMAGE_ARM_LINUX_CLANG: embeddedlinux/arm-linux-gnueabihf-clang:13

stages:
  - build-GCC
  - build-Clang
  - quality
  - trigger
  - deploy

include:
  - "/.gitlab/ci/build.yml"
  - "/.gitlab/ci/deploy.yml"
  - "/.gitlab/ci/quality.yml"
  - "/.gitlab/ci/trigger.yml"
