.Build_Linux:
  tags:
    - cet_build
  needs: []
  artifacts:
    name: "${CI_JOB_NAME}_${CI_JOB_ID}"
    expire_in: 2 weeks
    paths:
      - ${CI_JOB_NAME}/bin
  script:
    - mkdir ${CI_JOB_NAME}
    - cd ${CI_JOB_NAME}

    # Build application.
    - cmake .. -DTOOLCHAIN=${Toolchain} -DCMAKE_BUILD_TYPE=${BuildType}
    - make hal-gpio
    - make hal-i2c
    - make hal-spi
    - make hal-uart

.Build_Linux_ARM_Clang:
  extends: .Build_Linux
  stage: build-Clang
  image: ${DOCKER_IMAGE_ARM_LINUX_CLANG}
  variables:
    Toolchain: "arm-linux-gnueabihf-clang"

.Build_Linux_ARM_GCC:
  extends: .Build_Linux
  stage: build-GCC
  image: ${DOCKER_IMAGE_ARM_LINUX_GCC}
  variables:
    Toolchain: "arm-linux-gnueabihf-gcc"

.Build_Linux_Clang:
  extends: .Build_Linux
  stage: build-Clang
  image: ${DOCKER_IMAGE_CLANG}
  variables:
    Toolchain: "clang"

.Build_Linux_GCC:
  extends: .Build_Linux
  stage: build-GCC
  image: ${DOCKER_IMAGE_GCC}
  variables:
    Toolchain: "gcc"

Linux_ARM_Clang_Debug_Build:
  extends: .Build_Linux_ARM_Clang
  variables:
    BuildType: "Debug"

Linux_ARM_Clang_Release_Build:
  extends: .Build_Linux_ARM_Clang
  only:
    - master
  variables:
    BuildType: "Release"

Linux_ARM_GCC_Debug_Build:
  extends: .Build_Linux_ARM_GCC
  variables:
    BuildType: "Debug"

Linux_ARM_GCC_Release_Build:
  extends: .Build_Linux_ARM_GCC
  only:
    - master
  variables:
    BuildType: "Release"

Linux_Clang_Debug_Build:
  extends: .Build_Linux_Clang
  variables:
    BuildType: "Debug"

Linux_Clang_Release_Build:
  extends: .Build_Linux_Clang
  only:
    - master
  variables:
    BuildType: "Release"

Linux_GCC_Debug_Build:
  extends: .Build_Linux_GCC
  variables:
    BuildType: "Debug"

Linux_GCC_Release_Build:
  extends: .Build_Linux_GCC
  only:
    - master
  variables:
    BuildType: "Release"
